linters-settings:
  errcheck:
    ignore: ''
  goconst:
    min-len: 3
    min-occurrences: 3
  revive:
    rules:
      - name: unexported-return
        disabled: true
  gocyclo:
    min-complexity: 14
  misspell:
    locale: US
  staticcheck:
    checks:
      - all

linters:
  enable:
    - unused
    - errcheck
    - revive
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - govet
    - gosec
    - gocyclo
    - gofmt
    - goimports
    - goconst
    - gocritic
    - typecheck

run:
  timeout: 1m
  issues-exit-code: 1
  tests: true

output:
  print-issued-lines: true
  print-linter-name: true
