linters:
  enable:
    - gofmt
    - goimports
    - gci
  disable:
    - gochecknoglobals
    - goerr113
    - gomnd
    - gosimple
    - scopelint
    - exhaustivestruct
    - nestif
    - prealloc
    - nakedret
    - wsl
    - bodyclose
    - goconst
    - wsl
    - dupl
    - funlen
    - testpackage
    - interfacer
    - unparam
    - golint
    - godot
    - forbidigo
    - cyclop
    - gocritic
    - stylecheck
    - varcheck
    - maligned
    - depguard
    - tagliatelle
    - unconvert
    - wrapcheck
    - misspell
    - gocognit
    - lll
    - scopelint
    - gosec

linters-settings:
  staticcheck:
    checks:
      - all
  govet:
    enable-all: true

run:
  timeout: 5m